services:
  next-devops-test:
    image: ghcr.io/fadibouch/cours-devops/next-devops:develop
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next-test.rule=Host(`52.5.66.97`)"
      - "traefik.http.routers.next-test.entrypoints=web"
      - "traefik.http.middlewares.test-auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
      - "traefik.http.routers.next-test.middlewares=test-auth@docker"
    networks:
      - web

networks:
  web:
    external: true
    name: web
