on: [push]

jobs:

  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps: 
      - uses: actions/checkout@v4

      - name: Login to GitHub Container registery
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - id: lower-repo
      #   name: Repository to lowercase
      #   run: |
      #     echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
      # TO USE:  ${{ steps.lower-repo.outputs.repository }}


      # - name: Build and push Docker image (manual)
      #   run: | 
      #     docker build -t ghcr.io/${{ github.repository }}/next-devops:latest .
      #     docker push -t ghcr.io/${{ github.repository }}/next-devops:latest

      - name: Build and push Docker image (Docker action)
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/fadibouch/cours-devops/next-devops:${{ github.ref_name }}

  deploy-docker-prod:
    needs: build-docker
    uses: /mnt/c/Users/G513/Desktop/CESI/CDA-1/DevOps/next-cda24/.github/workflows/deploy-docker.yml@main
    with:
      env: prod
      branch: main
      url: http://ec2-52-5-66-97.compute-1.amazonaws.com/
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-docker-test:
    needs: build-docker
    uses: /mnt/c/Users/G513/Desktop/CESI/CDA-1/DevOps/next-cda24/.github/workflows/deploy-docker.yml@main
    with:
      env: test
      branch: develop
      url: http://ec2-52-5-66-97.compute-1.amazonaws.com/:8080
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
