on: [push]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm audit --audit-level=high

  test:
    strategy:
      matrix:
        browser: [chrome, edge]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: run Cypress test 
        uses: cypress-io/github-action@v6
        with: 
          install: true
          start: npm run dev
          browser: ${{ matrix.browser }}
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos/
          retention-days: 5
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          retention-days: 5

  build-docker:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps: 
      - uses: actions/checkout@v4

      - name: Login to GitHub Container registery
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push Docker image (manual)
      #   run: | 
      #     docker build -t ghcr.io/${{ github.repository }}/next-devops:latest .
      #     docker push -t ghcr.io/${{ github.repository }}/next-devops:latest

      - name: Build and push Docker image (Docker action)
        uses: docker/build-push-action@v6
        with:
          context: .
          target: next
          push: true
          tags: ghcr.io/fadibouch/cours-devops/next-devops:${{ github.ref_name }}

  deploy-prod:
    needs: build-docker
    uses: fadibouch/cours-devops/.github/workflows/deploy.yml@main
    with:
      env: prod
      branch: main
      url: http://ec2-52-5-66-97.compute-1.amazonaws.com/
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-test:
    needs: build-docker
    uses: fadibouch/cours-devops/.github/workflows/deploy.yml@main
    with:
      env: test
      branch: develop
      url: http://ec2-52-5-66-97.compute-1.amazonaws.com/:8080
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
