on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ls -lah
      - uses: actions/checkout@v4
      - run: ls -lah
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json')}}
      - run: | 
          npm install
          npm run build

  test:
    strategy:
      matrix:
        browser: [chrome, edge]
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_modules
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json')}}
      - name: run Cypress test 
        uses: cypress-io/github-action@v6
        with: 
          install: false
          start: npm run dev
          browser: ${{ matrix.browser }}
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos/
          retention-days: 5
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          retention-days: 5
        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH connection
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/cours-devops
            git pull 
            pm2 restart cours-devops